package users

import (
	"errors"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/formatters"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/requests"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/responses"
	validator "github.com/max-fletcher/golang_web_server_boilerplate/helpers/validation"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
	common_errors "github.com/max-fletcher/golang_web_server_boilerplate/internal/errors"
)

// same as the handler in internal/handler.go, but will create a new handler instance that is separate from that
type Handler struct {
	DB      *db.Queries // Reference to a DB connection. Will be used to query data form DB.
	service Service
}

func New(db *db.Queries) *Handler {
	return &Handler{
		DB:      db,
		service: NewService(db),
	}
}

func (handler *Handler) Create(w http.ResponseWriter, r *http.Request) {
	params := CreateUserRequest{}
	// since DecodeJSON return a boolean, just use a condition on the function directly
	// An error response will be thrown fromt the function inside
	// The important part here is to pass a [pointer to params] not [params] directly, else a copy will be passed
	if !requests.DecodeJSON(w, r, &params) {
		return
	}

	if err := params.Validate(); err != nil {
		responses.ValidationErrorWithFields(w, err)
		return
	}

	// 1st param: context for the request
	// 2nd param: the struct that we want to pass so it saves the underlying data in DB
	user, err := handler.service.Create(r.Context(), params)
	if err != nil {
		var emailExistsErr ErrUserWithEmailAlreadyExists // will store error if type matches in errors.As(...)
		if errors.As(err, &emailExistsErr) {
			responses.ConflictError(w, emailExistsErr.Error())
			return
		}

		// This block ensures the error thrown when finding user using GetUserById is not a result of say, database connection error
		var userFetchFailedErr ErrUserFetchFailed // will store error if type matches in errors.As(...)
		if errors.As(err, &userFetchFailedErr) {
			responses.InternalServerError(w, userFetchFailedErr.Error())
			return
		}

		var hashPasswordErr common_errors.ErrHashingPassword // will store error if type matches in errors.As(...)
		if errors.As(err, &hashPasswordErr) {
			responses.InternalServerError(w, hashPasswordErr.Error())
			return
		}

		var hashingPasswordErr ErrUserFetchFailed // will store error if type matches in errors.As(...)
		if errors.As(err, &hashingPasswordErr) {
			responses.InternalServerError(w, err.Error())
			return
		}

		var userCreateFailedErr ErrUserCreateFailed // will store error if type matches in errors.As(...)
		if errors.As(err, &userCreateFailedErr) {
			responses.InternalServerError(w, userCreateFailedErr.Error())
			return
		}

		responses.InternalServerError(w, "Something went wrong. Please try again.")
		return
	}

	responses.RespondWithSuccess(w, http.StatusCreated, "Created successfully", formatters.DatabaseUserToUser(user))
}

// handler method that handles fetching all users. The addition of (handler *Handler)
// turns it into a method for handler.
func (handler *Handler) GetAll(w http.ResponseWriter, r *http.Request) {
	pagination, validationErrors := validator.BaseValidatePagination(r.URL.Query())

	if len(validationErrors) > 0 {
		responses.ValidationErrorWithFields(w, validationErrors)
		return
	}

	params := db.GetUsersParams{ // db.GetUsersParams is generated by sqlc. Used to pass params to an sqlc query
		Limit:  int32(pagination.Limit),
		Offset: int32(pagination.Offset),
	}

	// 1st param: context for the request
	users, err := handler.service.GetAll(r.Context(), params)
	if err != nil {
		var usersFetchFailedErr ErrUsersFetchFailed // will store error if type matches in errors.As(...)
		if errors.As(err, &usersFetchFailedErr) {
			responses.InternalServerError(w, usersFetchFailedErr.Error())
			return
		}

		responses.InternalServerErrorSWW(w)
		return
	}

	responses.RespondWithSuccess(w, http.StatusOK, "Fetched successfully", formatters.DatabaseUsersToUsers(users))
}

func (handler *Handler) GetByID(w http.ResponseWriter, r *http.Request) {
	userId := chi.URLParam(r, "id")
	id, err := uuid.Parse(userId)
	if err != nil {
		responses.BadRequestError(w, "Invalid user ID")
		return
	}

	// 1st param: context for the request
	// 2nd param: id(type uuid) param
	user, err := handler.service.GetByID(r.Context(), id)
	if err != nil {
		var userWithIdNotFoundErr ErrUserWithIdNotFound
		if errors.As(err, &userWithIdNotFoundErr) {
			responses.NotFoundError(w, userWithIdNotFoundErr.Error())
			return
		}

		responses.InternalServerErrorSWW(w)
		return
	}

	responses.RespondWithSuccess(w, http.StatusOK, "Fetched successfully", formatters.DatabaseUserToUser(user))
}
