package users

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	id_helpers "github.com/max-fletcher/golang_web_server_boilerplate/helpers/ID"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/formatters"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/requests"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/responses"
	validator "github.com/max-fletcher/golang_web_server_boilerplate/helpers/validation"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
	common_errors "github.com/max-fletcher/golang_web_server_boilerplate/internal/errors"
)

// same as the handler in internal/handler.go, but will create a new handler instance that is separate from that
type Handler struct {
	DB      *db.Queries // Reference to a DB connection. Will be used to query data form DB.
	service Service
}

func New(db *db.Queries) *Handler {
	return &Handler{
		DB:      db,
		service: NewService(db),
	}
}

func (handler *Handler) Create(w http.ResponseWriter, r *http.Request) error {
	params := CreateUserRequest{}
	// Passing a [pointer to params] not [params] directly, else a copy will be passed
	if err := requests.DecodeJSON(r, &params); err != nil {
		return err
	}

	if err := params.Validate(); err != nil {
		return err
	}

	// 1st param: context for the request
	// 2nd param: the struct that we want to pass so it saves the underlying data in DB
	user, err := handler.service.Create(r.Context(), params)
	if err != nil {
		return err
	}

	responses.RespondWithSuccess(w, http.StatusCreated, "Created successfully", formatters.DatabaseUserToUser(user))

	return nil
}

func (handler *Handler) GetAll(w http.ResponseWriter, r *http.Request) error {
	pagination, validationErrors := validator.BaseValidatePagination(r.URL.Query())

	if len(validationErrors) > 0 {
		return common_errors.ErrValidationError{
			Errors: validationErrors,
		}
	}

	params := db.GetUsersParams{ // db.GetUsersParams is generated by sqlc. Used to pass params to an sqlc query
		Limit:  int32(pagination.Limit),
		Offset: int32(pagination.Offset),
	}

	// 1st param: context for the request
	users, err := handler.service.GetAll(r.Context(), params)
	if err != nil {
		return err
	}

	responses.RespondWithSuccess(w, http.StatusOK, "Fetched successfully", formatters.DatabaseUsersToUsers(users))

	return nil
}

func (handler *Handler) GetByID(w http.ResponseWriter, r *http.Request) error {
	id, err := id_helpers.ParseUUID(chi.URLParam(r, "id"))
	if err != nil {
		return err
	}

	// 1st param: context for the request
	// 2nd param: id(type uuid) param
	user, err := handler.service.GetByID(r.Context(), id)
	if err != nil {
		return err
	}

	responses.RespondWithSuccess(w, http.StatusOK, "Fetched successfully", formatters.DatabaseUserToUser(user))

	return nil
}
