package users

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/numbers"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
)

type Repository interface {
	Create(ctx context.Context, params db.CreateUserParams) (db.User, error)
	GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.User, error)
	GetAllCount(ctx context.Context, filterString string) (int, error)
	GetByID(ctx context.Context, id uuid.UUID) (db.User, error)
	GetByEmail(ctx context.Context, email string) (db.User, error)
	Update(ctx context.Context, params db.UpdateUserParams) (db.User, error)
	Delete(ctx context.Context, id uuid.UUID) (int64, error)
}

type repository struct {
	DB *db.Queries // Reference to a DB connection. Will be used to query data form DB.
}

func NewRepository(db *db.Queries) *repository {
	return &repository{
		DB: db,
	}
}

// No need to pass the entire response writer for these repository functions. Just passing the context from response writer(r.Context()) from where
// this is called from (i.e service) works just fine instead of passing the response writer, then using r.Context() as first param of sqlc function

func (repository *repository) Create(ctx context.Context, params db.CreateUserParams) (db.User, error) {
	return repository.DB.CreateUser(ctx, db.CreateUserParams{
		ID:        uuid.New(),
		Name:      params.Name,
		Email:     params.Email,
		Password:  params.Password,
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
	})
}

func (repository *repository) GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.User, error) {
	params := db.GetUsersParams{ // db.GetUsersParams is generated by sqlc. Used to pass params to an sqlc query
		Column1: filterString,
		Limit:   int32(limit),
		Offset:  int32(offset),
	}
	return repository.DB.GetUsers(ctx, params)
}

func (repository *repository) GetAllCount(ctx context.Context, filterString string) (int, error) {
	countInt64, err := repository.DB.GetUsersCount(ctx, filterString)
	count, err := numbers.BigInt64ToInt(countInt64)
	return count, err
}

func (repository *repository) GetByID(ctx context.Context, id uuid.UUID) (db.User, error) {
	return repository.DB.GetUserById(ctx, id)
}

func (repository *repository) GetByEmail(ctx context.Context, email string) (db.User, error) {
	return repository.DB.GetUserByEmail(ctx, email)
}

func (repository *repository) Update(ctx context.Context, params db.UpdateUserParams) (db.User, error) {
	return repository.DB.UpdateUser(ctx, db.UpdateUserParams{
		ID:        params.ID,
		Name:      params.Name,
		Email:     params.Email,
		Password:  params.Password,
		UpdatedAt: time.Now().UTC(),
	})
}

func (repository *repository) Delete(ctx context.Context, id uuid.UUID) (int64, error) {
	return repository.DB.DeleteUser(ctx, id)
}
