package posts_with_users

import (
	"context"

	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
)

type Repository interface {
	GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetPostsWithUserRow, error)
	// GetAllCount(ctx context.Context, filterString string) (int, error)
	GetByID(ctx context.Context, id uuid.UUID) (db.GetPostWithUserByIdRow, error)
}

type repository struct {
	DB *db.Queries // Reference to a DB connection. Will be used to query data form DB.
}

func NewRepository(database *db.Queries) *repository {
	return &repository{
		DB: database,
	}
}

// No need to pass the entire response writer for these repository functions. Just passing the context from response writer(r.Context()) from where
// this is called from (i.e service) works just fine instead of passing the response writer, then using r.Context() as first param of sqlc function

func (repository *repository) GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetPostsWithUserRow, error) {
	params := db.GetPostsWithUserParams{ // db.GetUsersParams is generated by sqlc. Used to pass params to an sqlc query
		Column1: filterString,
		Limit:   int32(limit),
		Offset:  int32(offset),
	}
	return repository.DB.GetPostsWithUser(ctx, params)
}

// func (repository *repository) GetAllCount(ctx context.Context, filterString string) (int, error) {
// 	countInt64, err := repository.DB.GetUsersCount(ctx, filterString)
// 	count, err := numbers.BigInt64ToInt(countInt64)
// 	return count, err
// }

func (repository *repository) GetByID(ctx context.Context, id uuid.UUID) (db.GetPostWithUserByIdRow, error) {
	return repository.DB.GetPostWithUserById(ctx, id)
}
