package acl

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/numbers"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/modules/permissions"
)

type Repository interface {
	Create(ctx context.Context, params db.CreateRolePermissionParams) (db.RolePermission, error)
	GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetUsersWithRolesAndPermissionsRow, error)
	GetAllCount(ctx context.Context, filterString string) (int, error)
	GetByUserID(ctx context.Context, id uuid.UUID) ([]db.GetUserWithRolesAndPermissionsByUserIDRow, error)
	UserHasPermission(ctx context.Context, userID uuid.UUID, moduleName permissions.EnumModule, permissionName db.PermissionNamesEnum) (bool, error)
	DeleteByID(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteByRoleIDAndPermissionID(ctx context.Context, roleID uuid.UUID, PermissionID uuid.UUID) (int64, error)
}

type repository struct {
	DB *db.Queries // Reference to a DB connection. Will be used to query data form DB.
}

func NewRepository(database *db.Queries) *repository {
	return &repository{
		DB: database,
	}
}

// No need to pass the entire response writer for these repository functions. Just passing the context from response writer(r.Context()) from where
// this is called from (i.e service) works just fine instead of passing the response writer, then using r.Context() as first param of sqlc function

func (repository *repository) Create(ctx context.Context, params db.CreateRolePermissionParams) (db.RolePermission, error) {
	return repository.DB.CreateRolePermission(ctx, db.CreateRolePermissionParams{
		ID:           uuid.New(),
		RoleID:       params.RoleID,
		PermissionID: params.PermissionID,
		CreatedAt:    time.Now().UTC(),
		UpdatedAt:    time.Now().UTC(),
	})
}

func (repository *repository) GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetUsersWithRolesAndPermissionsRow, error) {
	params := db.GetUsersWithRolesAndPermissionsParams{ // db.GetPostsParams is generated by sqlc. Used to pass params to an sqlc query
		Column1: filterString,
		Limit:   int32(limit),
		Offset:  int32(offset),
	}
	return repository.DB.GetUsersWithRolesAndPermissions(ctx, params)
}

func (repository *repository) GetAllCount(ctx context.Context, filterString string) (int, error) {
	countInt64, err := repository.DB.GetRolePermissionUsersCount(ctx, filterString)
	count, err := numbers.BigInt64ToInt(countInt64)
	return count, err
}

func (repository *repository) GetByUserID(ctx context.Context, id uuid.UUID) ([]db.GetUserWithRolesAndPermissionsByUserIDRow, error) {
	return repository.DB.GetUserWithRolesAndPermissionsByUserID(ctx, id)
}

func (repository *repository) UserHasPermission(ctx context.Context, userID uuid.UUID, moduleName permissions.EnumModule, permissionName db.PermissionNamesEnum) (bool, error) {
	return repository.DB.UserHasPermission(ctx, db.UserHasPermissionParams{
		Name:   string(moduleName),
		Name_2: permissionName,
	})
}

func (repository *repository) DeleteByID(ctx context.Context, id uuid.UUID) (int64, error) {
	return repository.DB.DeleteRolePermissionByID(ctx, id)
}

func (repository *repository) DeleteByRoleIDAndPermissionID(ctx context.Context, roleID uuid.UUID, PermissionID uuid.UUID) (int64, error) {
	params := db.DeleteRolePermissionByRoleIDAndPermissionIDParams{
		RoleID:       roleID,
		PermissionID: PermissionID,
	}
	return repository.DB.DeleteRolePermissionByRoleIDAndPermissionID(ctx, params)
}
