package posts

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/numbers"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
)

type Repository interface {
	Create(ctx context.Context, params db.CreatePostParams) (db.Post, error)
	GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.Post, error)
	GetAllCount(ctx context.Context, filterString string) (int, error)
	GetByID(ctx context.Context, id uuid.UUID) (db.Post, error)
	Update(ctx context.Context, params db.UpdatePostParams) (db.Post, error)
	Delete(ctx context.Context, id uuid.UUID) (int64, error)
}

type repository struct {
	DB *db.Queries // Reference to a DB connection. Will be used to query data form DB.
}

func NewRepository(database *db.Queries) *repository {
	return &repository{
		DB: database,
	}
}

// No need to pass the entire response writer for these repository functions. Just passing the context from response writer(r.Context()) from where
// this is called from (i.e service) works just fine instead of passing the response writer, then using r.Context() as first param of sqlc function

func (repository *repository) Create(ctx context.Context, params db.CreatePostParams) (db.Post, error) {
	// #TODO: File uploader

	return repository.DB.CreatePost(ctx, db.CreatePostParams{
		ID:      uuid.New(),
		Title:   params.Title,
		Content: params.Content,
		// Photo:     params.Photo,
		UserID:    params.UserID,
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
	})
}

func (repository *repository) GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.Post, error) {
	params := db.GetPostsParams{ // db.GetPostsParams is generated by sqlc. Used to pass params to an sqlc query
		Column1: filterString,
		Limit:   int32(limit),
		Offset:  int32(offset),
	}
	return repository.DB.GetPosts(ctx, params)
}

func (repository *repository) GetAllCount(ctx context.Context, filterString string) (int, error) {
	countInt64, err := repository.DB.GetPostsCount(ctx, filterString)
	count, err := numbers.BigInt64ToInt(countInt64)
	return count, err
}

func (repository *repository) GetByID(ctx context.Context, id uuid.UUID) (db.Post, error) {
	return repository.DB.GetPostById(ctx, id)
}

func (repository *repository) Update(ctx context.Context, params db.UpdatePostParams) (db.Post, error) {
	return repository.DB.UpdatePost(ctx, db.UpdatePostParams{
		ID:      params.ID,
		Title:   params.Title,
		Content: params.Content,
		// Photo:     params.Photo,
		UserID:    params.UserID,
		UpdatedAt: time.Now().UTC(),
	})
}

func (repository *repository) Delete(ctx context.Context, id uuid.UUID) (int64, error) {
	return repository.DB.DeletePost(ctx, id)
}
