package user_roles

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/numbers"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
)

type Repository interface {
	Create(ctx context.Context, params db.CreateUserRoleParams) (db.UserRole, error)
	GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetUserRolesRow, error)
	GetAllCount(ctx context.Context, filterString string) (int, error)
	GetByID(ctx context.Context, id uuid.UUID) (db.GetUserRoleByIdRow, error)
	GetByUserID(ctx context.Context, id uuid.UUID) ([]db.GetUserRolesByUserIDRow, error)
	GetUserRoleByUserIDAndRoleID(ctx context.Context, roleID uuid.UUID, userID uuid.UUID) (db.GetUserRoleByUserIDAndRoleIDRow, error)
	DeleteByID(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteByUserIDAndRoleID(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (int64, error)
}

type repository struct {
	DB *db.Queries // Reference to a DB connection. Will be used to query data form DB.
}

func NewRepository(database *db.Queries) *repository {
	return &repository{
		DB: database,
	}
}

// No need to pass the entire response writer for these repository functions. Just passing the context from response writer(r.Context()) from where
// this is called from (i.e service) works just fine instead of passing the response writer, then using r.Context() as first param of sqlc function

func (repository *repository) Create(ctx context.Context, params db.CreateUserRoleParams) (db.UserRole, error) {
	return repository.DB.CreateUserRole(ctx, db.CreateUserRoleParams{
		ID:        uuid.New(),
		UserID:    params.UserID,
		RoleID:    params.RoleID,
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
	})
}

func (repository *repository) GetAll(ctx context.Context, filterString string, limit int, offset int) ([]db.GetUserRolesRow, error) {
	params := db.GetUserRolesParams{ // db.GetPostsParams is generated by sqlc. Used to pass params to an sqlc query
		Column1: filterString,
		Limit:   int32(limit),
		Offset:  int32(offset),
	}
	return repository.DB.GetUserRoles(ctx, params)
}

func (repository *repository) GetAllCount(ctx context.Context, filterString string) (int, error) {
	countInt64, err := repository.DB.GetUserRolesCount(ctx, filterString)
	count, err := numbers.BigInt64ToInt(countInt64)
	return count, err
}

func (repository *repository) GetByID(ctx context.Context, id uuid.UUID) (db.GetUserRoleByIdRow, error) {
	return repository.DB.GetUserRoleById(ctx, id)
}

func (repository *repository) GetByUserID(ctx context.Context, id uuid.UUID) ([]db.GetUserRolesByUserIDRow, error) {
	return repository.DB.GetUserRolesByUserID(ctx, id)
}

func (repository *repository) GetUserRoleByUserIDAndRoleID(ctx context.Context, roleID uuid.UUID, userID uuid.UUID) (db.GetUserRoleByUserIDAndRoleIDRow, error) {
	params := db.GetUserRoleByUserIDAndRoleIDParams{
		UserID: userID,
		RoleID: roleID,
	}

	return repository.DB.GetUserRoleByUserIDAndRoleID(ctx, params)
}

func (repository *repository) DeleteByID(ctx context.Context, id uuid.UUID) (int64, error) {
	return repository.DB.DeleteUserRoleById(ctx, id)
}

func (repository *repository) DeleteByUserIDAndRoleID(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (int64, error) {
	params := db.DeleteUserRoleByUserIDAndRoleIdParams{
		UserID: userID,
		RoleID: roleID,
	}
	return repository.DB.DeleteUserRoleByUserIDAndRoleId(ctx, params)
}
