package handlers

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is" // provides email valdiation and such
	"github.com/google/uuid"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/crypto"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/formatters"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/requests"
	"github.com/max-fletcher/golang_web_server_boilerplate/helpers/responses"
	validator "github.com/max-fletcher/golang_web_server_boilerplate/helpers/validation"
	"github.com/max-fletcher/golang_web_server_boilerplate/internal/db"
)

// Struct to be validated
type CreateUserRequest struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

// Rules
func (params CreateUserRequest) Validate() error {
	return validation.ValidateStruct(&params,
		validation.Field(
			&params.Name,
			validation.Required.Error("name is required"),
			validation.Length(2, 100).Error("name must be between 2 and 100 characters"),
		),
		validation.Field(
			&params.Email,
			validation.Required.Error("Email is required"),
			is.Email.Error("Email must be a valid email address"),
		),
		validation.Field(
			&params.Password,
			validation.Required.Error("Password is required"),
			validation.Length(8, 100).Error("Password must be at least 8 characters"),
		),
		validation.Field(
			&params.ConfirmPassword,
			validation.Required.Error("Confirm password is required"),
			passwordsMatch(params.Password),
		),
	)
}

// custom validation rule used above
func passwordsMatch(password string) validation.Rule {
	return validation.By(func(value interface{}) error {
		confirmPassword, ok := value.(string)
		if !ok {
			return errors.New("invalid password confirmation")
		}

		if confirmPassword != password {
			return errors.New("passwords do not match")
		}

		return nil
	})
}

func (handler *Handler) CreateUser(w http.ResponseWriter, r *http.Request) {
	params := CreateUserRequest{}
	// since DecodeJSON return a boolean, just use a condition on the function directly
	// The important part here is to pass a [pointer to params] not [params] directly, else a copy will be passed
	if !requests.DecodeJSON(w, r, &params) {
		return
	}

	if err := params.Validate(); err != nil {
		responses.ValidationErrorWithFields(w, err)
		return
	}

	hashedPassword, err := crypto.HashPassword(params.Password)
	if err != nil {
		responses.RespondWithError(w, 400, fmt.Sprintf("Error hashing password: %v", err))
		return
	}

	// 1st param: context for the request
	// 2nd param: the struct that we want to pass so it saves the underlying data in DB
	user, err := handler.DB.CreateUser(r.Context(), db.CreateUserParams{
		ID:        uuid.New(),
		Name:      params.Name,
		Email:     params.Email,
		Password:  hashedPassword,
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
	})
	if err != nil {
		databaseErrorString := fmt.Sprintf("Couldn't create user: %v", err)
		responses.BadRequestError(w, databaseErrorString)
		return
	}

	responses.RespondWithSuccess(w, http.StatusOK, "Created successfully", formatters.DatabaseUserToUser(user))
}

// handler method that handles fetching all users. The addition of (handler *Handler)
// turns it into a method for handler.
func (handler *Handler) GetAllUsers(w http.ResponseWriter, r *http.Request) {
	pagination, validationErrors := validator.BaseValidatePagination(r.URL.Query())

	if len(validationErrors) > 0 {
		responses.ValidationErrorWithFields(w, validationErrors)
		return
	}

	params := db.GetUsersParams{ // db.GetUsersParams is generated by sqlc. Used to pass params to an sqlc query
		Limit:  int32(pagination.Limit),
		Offset: int32(pagination.Offset),
	}

	// 1st param: context for the request
	users, err := handler.DB.GetUsers(r.Context(), params)
	if err != nil {
		responses.RespondWithError(w, 400, fmt.Sprintf("Failed to fetch users: %v", err))
		return
	}

	responses.RespondWithJSON(w, 200, responses.SuccessResponse{
		Code:    200,
		Status:  "ok",
		Message: "Fetched successfully",
		Data:    formatters.DatabaseUsersToUsers(users),
	})
}
