// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createModule = `-- name: CreateModule :one

INSERT INTO modules (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, updated_at
`

type CreateModuleParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, createModule,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModuleById = `-- name: GetModuleById :one
SELECT id, name, created_at, updated_at 
FROM modules 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetModuleById(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModuleById, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModules = `-- name: GetModules :many
SELECT id, name, created_at, updated_at 
FROM modules 
WHERE
    ($1 = '' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetModulesParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) GetModules(ctx context.Context, arg GetModulesParams) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, getModules, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModulesCount = `-- name: GetModulesCount :one
SELECT COUNT(*)
FROM modules 
WHERE
    ($1 = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) GetModulesCount(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getModulesCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
