// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (id, name, module_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, module_id, created_at, updated_at
`

type CreatePermissionParams struct {
	ID        uuid.UUID
	Name      PermissionNamesEnum
	ModuleID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.ModuleID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissions = `-- name: GetPermissions :many
SELECT id, name, module_id, created_at, updated_at 
FROM permissions 
WHERE
    ($1 = '' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetPermissionsParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) GetPermissions(ctx context.Context, arg GetPermissionsParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getPermissions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsById = `-- name: GetPermissionsById :one
SELECT id, name, module_id, created_at, updated_at 
FROM permissions 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPermissionsById(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionsById, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionsCount = `-- name: GetPermissionsCount :one
SELECT COUNT(*)
FROM permissions 
WHERE
    ($1 = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) GetPermissionsCount(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPermissionsCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
