// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts-with-queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getPostWithUserById = `-- name: GetPostWithUserById :one

SELECT 
  posts.id,
  posts.title,
  posts.content,
  posts.photo,
  posts.user_id,
  posts.created_at AS post_created_at,
  posts.updated_at AS post_updated_at,
  users.id AS user_id,
  users.name AS user_name,
  users.email AS user_email
FROM posts 
INNER JOIN users 
ON posts.user_id = users.id
WHERE posts.id = $1
LIMIT 1
`

type GetPostWithUserByIdRow struct {
	ID            uuid.UUID
	Title         string
	Content       sql.NullString
	Photo         sql.NullString
	UserID        uuid.UUID
	PostCreatedAt time.Time
	PostUpdatedAt time.Time
	UserID_2      uuid.UUID
	UserName      string
	UserEmail     string
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) GetPostWithUserById(ctx context.Context, id uuid.UUID) (GetPostWithUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostWithUserById, id)
	var i GetPostWithUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Photo,
		&i.UserID,
		&i.PostCreatedAt,
		&i.PostUpdatedAt,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getPostsWithUser = `-- name: GetPostsWithUser :many
SELECT 
  posts.id,
  posts.title,
  posts.content,
  posts.photo,
  posts.user_id,
  posts.created_at AS post_created_at,
  posts.updated_at AS post_updated_at,
  users.id AS user_id,
  users.name AS user_name,
  users.email AS user_email
FROM posts 
INNER JOIN users 
ON posts.user_id = users.id
WHERE
    ($1 = '' OR posts.title ILIKE '%' || $1 || '%')
ORDER BY posts.created_at DESC
LIMIT $2
OFFSET $3
`

type GetPostsWithUserParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type GetPostsWithUserRow struct {
	ID            uuid.UUID
	Title         string
	Content       sql.NullString
	Photo         sql.NullString
	UserID        uuid.UUID
	PostCreatedAt time.Time
	PostUpdatedAt time.Time
	UserID_2      uuid.UUID
	UserName      string
	UserEmail     string
}

func (q *Queries) GetPostsWithUser(ctx context.Context, arg GetPostsWithUserParams) ([]GetPostsWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsWithUser, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsWithUserRow
	for rows.Next() {
		var i GetPostsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Photo,
			&i.UserID,
			&i.PostCreatedAt,
			&i.PostUpdatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
