// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one

INSERT INTO posts (id, title, content, photo, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, content, photo, user_id, created_at, updated_at
`

type CreatePostParams struct {
	ID        uuid.UUID
	Title     string
	Content   string
	Photo     sql.NullString
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Photo,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Photo,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1
RETURNING id, title, content, photo, user_id, created_at, updated_at
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPostById = `-- name: GetPostById :one
SELECT id, title, content, photo, user_id, created_at, updated_at 
FROM posts 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Photo,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, content, photo, user_id, created_at, updated_at 
FROM posts 
WHERE
    ($1 = '' OR title ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetPostsParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Photo,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsCount = `-- name: GetPostsCount :one
SELECT COUNT(*)
FROM posts 
WHERE
    ($1 = '' OR title ILIKE '%' || $1 || '%')
`

func (q *Queries) GetPostsCount(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostsCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2,
    content = $3,
    photo = $4,
    user_id = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, title, content, photo, user_id, created_at, updated_at
`

type UpdatePostParams struct {
	ID        uuid.UUID
	Title     string
	Content   string
	Photo     sql.NullString
	UserID    uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Photo,
		arg.UserID,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Photo,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
