// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRolePermission = `-- name: CreateRolePermission :one

INSERT INTO role_permissions (id, role_id, permission_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, role_id, permission_id, created_at, updated_at
`

type CreateRolePermissionParams struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
// The query:GetUsersWithRolesAndPermissions is using CTE
// The query:UserHasPermission returns a boolean
func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRowContext(ctx, createRolePermission,
		arg.ID,
		arg.RoleID,
		arg.PermissionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRolePermissionByID = `-- name: DeleteRolePermissionByID :execrows
DELETE FROM role_permissions
WHERE id = $1
RETURNING id, role_id, permission_id, created_at, updated_at
`

func (q *Queries) DeleteRolePermissionByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRolePermissionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRolePermissionByRoleIDAndPermissionID = `-- name: DeleteRolePermissionByRoleIDAndPermissionID :execrows
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
RETURNING id, role_id, permission_id, created_at, updated_at
`

type DeleteRolePermissionByRoleIDAndPermissionIDParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) DeleteRolePermissionByRoleIDAndPermissionID(ctx context.Context, arg DeleteRolePermissionByRoleIDAndPermissionIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRolePermissionByRoleIDAndPermissionID, arg.RoleID, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRolePermissionUsersCount = `-- name: GetRolePermissionUsersCount :one
SELECT COUNT(DISTINCT u.id)
FROM users AS u
INNER JOIN user_roles AS ur
    ON u.id = ur.user_id
INNER JOIN roles AS r
    ON r.id = ur.role_id
INNER JOIN role_permissions AS rp
    ON r.id = rp.role_id
INNER JOIN permissions AS p
    ON p.id = rp.permission_id
INNER JOIN modules AS m
    ON m.id = p.module_id
WHERE
    $1 = ''
    OR u.name ILIKE '%' || $1 || '%'
    OR r.name ILIKE '%' || $1 || '%'
    OR m.name ILIKE '%' || $1 || '%'
    OR p.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRolePermissionUsersCount(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRolePermissionUsersCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserWithRolesAndPermissionsByUserID = `-- name: GetUserWithRolesAndPermissionsByUserID :many
SELECT
    u.id,
    u.name,
    u.email,
    u.created_at,
    u.updated_at,
    r.name AS role_name,
    p.name AS permission_name,
    m.name AS module_name
FROM users AS u
INNER JOIN user_roles AS ur
    ON u.id = ur.user_id
INNER JOIN roles AS r
    ON r.id = ur.role_id
INNER JOIN role_permissions AS rp
    ON r.id = rp.role_id
INNER JOIN permissions AS p
    ON p.id = rp.permission_id
INNER JOIN modules AS m
    ON m.id = p.module_id
WHERE u.id = $1
ORDER BY r.name, m.name, p.name
`

type GetUserWithRolesAndPermissionsByUserIDRow struct {
	ID             uuid.UUID
	Name           string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RoleName       string
	PermissionName PermissionNamesEnum
	ModuleName     string
}

func (q *Queries) GetUserWithRolesAndPermissionsByUserID(ctx context.Context, id uuid.UUID) ([]GetUserWithRolesAndPermissionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithRolesAndPermissionsByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithRolesAndPermissionsByUserIDRow
	for rows.Next() {
		var i GetUserWithRolesAndPermissionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.PermissionName,
			&i.ModuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithRolesAndPermissions = `-- name: GetUsersWithRolesAndPermissions :many
WITH paginated_users AS (
    SELECT DISTINCT
        u.id,
        u.name,
        u.email,
        u.created_at,
        u.updated_at
    FROM users AS u
    INNER JOIN user_roles AS ur
        ON u.id = ur.user_id
    INNER JOIN roles AS r
        ON r.id = ur.role_id
    INNER JOIN role_permissions AS rp
        ON r.id = rp.role_id
    INNER JOIN permissions AS p
        ON p.id = rp.permission_id
    INNER JOIN modules AS m
        ON m.id = p.module_id
    WHERE
        $1 = ''
        OR u.name ILIKE '%' || $1 || '%'
        OR r.name ILIKE '%' || $1 || '%'
        OR m.name ILIKE '%' || $1 || '%'
        OR p.name ILIKE '%' || $1 || '%'
    ORDER BY u.created_at DESC
    LIMIT $2
    OFFSET $3
)
SELECT
    u.id,
    u.name,
    u.email,
    u.created_at,
    u.updated_at,
    r.name AS role_name,
    p.name AS permission_name,
    m.name AS module_name
FROM paginated_users AS u
INNER JOIN user_roles AS ur
    ON u.id = ur.user_id
INNER JOIN roles AS r
    ON r.id = ur.role_id
INNER JOIN role_permissions AS rp
    ON r.id = rp.role_id
INNER JOIN permissions AS p
    ON p.id = rp.permission_id
INNER JOIN modules AS m
    ON m.id = p.module_id
ORDER BY u.created_at DESC
`

type GetUsersWithRolesAndPermissionsParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type GetUsersWithRolesAndPermissionsRow struct {
	ID             uuid.UUID
	Name           string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RoleName       string
	PermissionName PermissionNamesEnum
	ModuleName     string
}

func (q *Queries) GetUsersWithRolesAndPermissions(ctx context.Context, arg GetUsersWithRolesAndPermissionsParams) ([]GetUsersWithRolesAndPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithRolesAndPermissions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithRolesAndPermissionsRow
	for rows.Next() {
		var i GetUsersWithRolesAndPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.PermissionName,
			&i.ModuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN role_permissions rp
        ON rp.role_id = ur.role_id
    INNER JOIN permissions p
        ON p.id = rp.permission_id
    INNER JOIN modules m
        ON m.id = p.module_id
    WHERE ur.user_id = $1
      AND m.name = $2
      AND p.name = $3
)
`

type UserHasPermissionParams struct {
	UserID uuid.UUID
	Name   string
	Name_2 PermissionNamesEnum
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasPermission, arg.UserID, arg.Name, arg.Name_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
