// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserRole = `-- name: CreateUserRole :one

INSERT INTO user_roles (id, user_id, role_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, role_id, created_at, updated_at
`

type CreateUserRoleParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRole,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserRoleById = `-- name: DeleteUserRoleById :execrows
DELETE FROM user_roles
WHERE id = $1
RETURNING id, user_id, role_id, created_at, updated_at
`

func (q *Queries) DeleteUserRoleById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserRoleById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserRoleByUserIDAndRoleId = `-- name: DeleteUserRoleByUserIDAndRoleId :execrows
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
RETURNING id, user_id, role_id, created_at, updated_at
`

type DeleteUserRoleByUserIDAndRoleIdParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) DeleteUserRoleByUserIDAndRoleId(ctx context.Context, arg DeleteUserRoleByUserIDAndRoleIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserRoleByUserIDAndRoleId, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserRoleById = `-- name: GetUserRoleById :one
SELECT id, user_id, role_id, created_at, updated_at 
FROM user_roles 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserRoleById(ctx context.Context, id uuid.UUID) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleById, id)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleByUserIDAndRoleID = `-- name: GetUserRoleByUserIDAndRoleID :one
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, r.name as role_name
FROM user_roles AS ur
INNER JOIN users AS u ON u.id = ur.user_id
INNER JOIN roles AS r ON r.id = ur.role_id
WHERE ur.user_id = $1
AND r.id = $2
`

type GetUserRoleByUserIDAndRoleIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetUserRoleByUserIDAndRoleIDRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  string
}

func (q *Queries) GetUserRoleByUserIDAndRoleID(ctx context.Context, arg GetUserRoleByUserIDAndRoleIDParams) (GetUserRoleByUserIDAndRoleIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByUserIDAndRoleID, arg.UserID, arg.ID)
	var i GetUserRoleByUserIDAndRoleIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, ur.role_id, r.name as role_name
FROM user_roles AS ur
INNER JOIN users AS u ON u.id = ur.user_id
INNER JOIN roles AS r ON r.id = ur.role_id
ORDER BY u.created_at DESC
LIMIT $1
OFFSET $2
`

type GetUserRolesParams struct {
	Limit  int32
	Offset int32
}

type GetUserRolesRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleID    uuid.UUID
	RoleName  string
}

func (q *Queries) GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]GetUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesRow
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesByUserID = `-- name: GetUserRolesByUserID :many
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, r.name as role_name
FROM user_roles AS ur
INNER JOIN users AS u ON u.id = ur.user_id
INNER JOIN roles AS r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

type GetUserRolesByUserIDRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  string
}

func (q *Queries) GetUserRolesByUserID(ctx context.Context, userID uuid.UUID) ([]GetUserRolesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesByUserIDRow
	for rows.Next() {
		var i GetUserRolesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesCount = `-- name: GetUserRolesCount :one
SELECT COUNT(*)
FROM user_roles
`

func (q *Queries) GetUserRolesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserRolesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
