// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserRole = `-- name: CreateUserRole :one

INSERT INTO user_roles (id, user_id, role_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, role_id, created_at, updated_at
`

type CreateUserRoleParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRole,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserRoleById = `-- name: DeleteUserRoleById :execrows
DELETE FROM user_roles
WHERE id = $1
RETURNING id, user_id, role_id, created_at, updated_at
`

func (q *Queries) DeleteUserRoleById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserRoleById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserRoleByUserIDAndRoleId = `-- name: DeleteUserRoleByUserIDAndRoleId :execrows
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
RETURNING id, user_id, role_id, created_at, updated_at
`

type DeleteUserRoleByUserIDAndRoleIdParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) DeleteUserRoleByUserIDAndRoleId(ctx context.Context, arg DeleteUserRoleByUserIDAndRoleIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserRoleByUserIDAndRoleId, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserRoleById = `-- name: GetUserRoleById :one
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, r.name as role_name
FROM user_roles AS ur
INNER JOIN users AS u 
  ON u.id = ur.user_id
INNER JOIN roles AS r 
  ON r.id = ur.role_id
WHERE ur.id = $1
`

type GetUserRoleByIdRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  string
}

func (q *Queries) GetUserRoleById(ctx context.Context, id uuid.UUID) (GetUserRoleByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleById, id)
	var i GetUserRoleByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
	)
	return i, err
}

const getUserRoleByUserIDAndRoleID = `-- name: GetUserRoleByUserIDAndRoleID :one
SELECT
    u.id,
    u.name,
    u.email,
    u.created_at,
    u.updated_at,
    r.name AS role_name
FROM user_roles AS ur
INNER JOIN users AS u
    ON u.id = ur.user_id
INNER JOIN roles AS r
    ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND ur.role_id = $2
`

type GetUserRoleByUserIDAndRoleIDParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

type GetUserRoleByUserIDAndRoleIDRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  string
}

func (q *Queries) GetUserRoleByUserIDAndRoleID(ctx context.Context, arg GetUserRoleByUserIDAndRoleIDParams) (GetUserRoleByUserIDAndRoleIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByUserIDAndRoleID, arg.UserID, arg.RoleID)
	var i GetUserRoleByUserIDAndRoleIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
WITH paginated_users AS (
  SELECT u.id, u.name, u.email, u.created_at, u.updated_at
  FROM users AS u
  WHERE
    $1 = ''
    OR u.name ILIKE '%' || $1 || '%'
    OR EXISTS (
        SELECT 1
        FROM user_roles AS ur
        INNER JOIN roles AS r
          ON r.id = ur.role_id
        WHERE ur.user_id = u.id
          AND r.name ILIKE '%' || $1 || '%'
    )
  ORDER BY u.created_at DESC
  LIMIT $2
  OFFSET $3
)
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, ur.role_id, r.name as role_name
FROM paginated_users AS u
LEFT JOIN user_roles AS ur 
  ON u.id = ur.user_id
LEFT JOIN roles AS r 
  ON r.id = ur.role_id
ORDER BY u.created_at DESC
`

type GetUserRolesParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type GetUserRolesRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleID    uuid.NullUUID
	RoleName  sql.NullString
}

func (q *Queries) GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]GetUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesRow
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesByUserID = `-- name: GetUserRolesByUserID :many
SELECT u.id, u.name, u.email, u.created_at, u.updated_at, r.name as role_name
FROM users AS u
LEFT JOIN user_roles AS ur
  ON u.id = ur.user_id
LEFT JOIN roles AS r 
  ON r.id = ur.role_id
WHERE u.id = $1
`

type GetUserRolesByUserIDRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  sql.NullString
}

func (q *Queries) GetUserRolesByUserID(ctx context.Context, id uuid.UUID) ([]GetUserRolesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRolesByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesByUserIDRow
	for rows.Next() {
		var i GetUserRolesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesCount = `-- name: GetUserRolesCount :one
SELECT COUNT(*)
FROM users AS u
WHERE
  $1 = ''
  OR u.name ILIKE '%' || $1 || '%'
  OR EXISTS (
      SELECT 1
      FROM user_roles AS ur
      INNER JOIN roles AS r
        ON r.id = ur.role_id
      WHERE ur.user_id = u.id
        AND r.name ILIKE '%' || $1 || '%'
  )
`

func (q *Queries) GetUserRolesCount(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserRolesCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
